package com.nezwork.ARSPOT;

/* This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int app_icon = 2130837504;
    }

    public static final class string {
        public static final int app_name = 2130903040;
    }
}
