package org.p004a.p005a.p025g.p026a;

/* renamed from: org.a.a.g.a.y */
enum C0413y {
    UNINITIATED,
    CHALLENGE_RECEIVED,
    MSG_TYPE1_GENERATED,
    MSG_TYPE2_RECEVIED,
    MSG_TYPE3_GENERATED,
    FAILED;

    static {
        UNINITIATED = new C0413y("UNINITIATED", 0);
        CHALLENGE_RECEIVED = new C0413y("CHALLENGE_RECEIVED", 1);
        MSG_TYPE1_GENERATED = new C0413y("MSG_TYPE1_GENERATED", 2);
        MSG_TYPE2_RECEVIED = new C0413y("MSG_TYPE2_RECEVIED", 3);
        MSG_TYPE3_GENERATED = new C0413y("MSG_TYPE3_GENERATED", 4);
        FAILED = new C0413y("FAILED", 5);
        C0413y[] yVarArr = {UNINITIATED, CHALLENGE_RECEIVED, MSG_TYPE1_GENERATED, MSG_TYPE2_RECEVIED, MSG_TYPE3_GENERATED, FAILED};
    }
}
