package com.jackhenry.android.p022a;

import com.fi6418.godough.R;

/* renamed from: com.jackhenry.android.a.h */
public final class C1361h {
    public static final int[] CalendarControl = {R.attr.dateDrawable, R.attr.dateTextColor, R.attr.dateTextSize, R.attr.dateShadowDx, R.attr.dateShadowDy, R.attr.dateShadowRadius, R.attr.dateShadowColor, R.attr.arrowOutlineColor, R.attr.arrowTopGradientColor, R.attr.arrowBotGradientColor, R.attr.dowTextColor, R.attr.dowTextSize, R.attr.dowShadowDx, R.attr.dowShadowDy, R.attr.dowShadowRadius, R.attr.dowShadowColor, R.attr.dayTextColor, R.attr.dayTextSize, R.attr.dayShadowDx, R.attr.dayShadowDy, R.attr.dayShadowRadius, R.attr.dayShadowColor, R.attr.dayDrawable, R.attr.dayNoSelectTextColor, R.attr.dayNoSelectTextSize, R.attr.dayNoSelectShadowDx, R.attr.dayNoSelectShadowDy, R.attr.dayNoSelectShadowRadius, R.attr.dayNoSelectShadowColor, R.attr.dayNoSelectDrawable, R.attr.dayWeekendTextColor, R.attr.dayWeekendTextSize, R.attr.dayWeekendShadowDx, R.attr.dayWeekendShadowDy, R.attr.dayWeekendShadowRadius, R.attr.dayWeekendShadowColor, R.attr.dayWeekendDrawable, R.attr.dayDiffMonthTextColor, R.attr.dayDiffMonthTextSize, R.attr.dayDiffMonthShadowDx, R.attr.dayDiffMonthShadowDy, R.attr.dayDiffMonthShadowRadius, R.attr.dayDiffMonthShadowColor, R.attr.dayDiffMonthDrawable, R.attr.todayDrawable, R.attr.todayDrawableKeepSquare, R.attr.todaySelectedDrawable, R.attr.todaySelectedDrawableKeepSquare, R.attr.selectedDrawable, R.attr.selectedDrawableKeepSquare, R.attr.gridLineColor, R.attr.selectedTextColor, R.attr.selectedTextSize, R.attr.selectedShadowDx, R.attr.selectedShadowDy, R.attr.selectedShadowRadius, R.attr.selectedShadowColor, R.attr.minimumDate, R.attr.maximumDate, R.attr.weekendSelectable, R.attr.timeDefault, R.attr.gridLinesVisible, R.attr.todayHighlighted, R.attr.yearNavigationVisible, R.attr.allowNullDate, R.attr.allowViewBeforeMinimum, R.attr.allowViewPastMaximum};
    public static final int CalendarControl_allowNullDate = 64;
    public static final int CalendarControl_allowViewBeforeMinimum = 65;
    public static final int CalendarControl_allowViewPastMaximum = 66;
    public static final int CalendarControl_arrowBotGradientColor = 9;
    public static final int CalendarControl_arrowOutlineColor = 7;
    public static final int CalendarControl_arrowTopGradientColor = 8;
    public static final int CalendarControl_dateDrawable = 0;
    public static final int CalendarControl_dateShadowColor = 6;
    public static final int CalendarControl_dateShadowDx = 3;
    public static final int CalendarControl_dateShadowDy = 4;
    public static final int CalendarControl_dateShadowRadius = 5;
    public static final int CalendarControl_dateTextColor = 1;
    public static final int CalendarControl_dateTextSize = 2;
    public static final int CalendarControl_dayDiffMonthDrawable = 43;
    public static final int CalendarControl_dayDiffMonthShadowColor = 42;
    public static final int CalendarControl_dayDiffMonthShadowDx = 39;
    public static final int CalendarControl_dayDiffMonthShadowDy = 40;
    public static final int CalendarControl_dayDiffMonthShadowRadius = 41;
    public static final int CalendarControl_dayDiffMonthTextColor = 37;
    public static final int CalendarControl_dayDiffMonthTextSize = 38;
    public static final int CalendarControl_dayDrawable = 22;
    public static final int CalendarControl_dayNoSelectDrawable = 29;
    public static final int CalendarControl_dayNoSelectShadowColor = 28;
    public static final int CalendarControl_dayNoSelectShadowDx = 25;
    public static final int CalendarControl_dayNoSelectShadowDy = 26;
    public static final int CalendarControl_dayNoSelectShadowRadius = 27;
    public static final int CalendarControl_dayNoSelectTextColor = 23;
    public static final int CalendarControl_dayNoSelectTextSize = 24;
    public static final int CalendarControl_dayShadowColor = 21;
    public static final int CalendarControl_dayShadowDx = 18;
    public static final int CalendarControl_dayShadowDy = 19;
    public static final int CalendarControl_dayShadowRadius = 20;
    public static final int CalendarControl_dayTextColor = 16;
    public static final int CalendarControl_dayTextSize = 17;
    public static final int CalendarControl_dayWeekendDrawable = 36;
    public static final int CalendarControl_dayWeekendShadowColor = 35;
    public static final int CalendarControl_dayWeekendShadowDx = 32;
    public static final int CalendarControl_dayWeekendShadowDy = 33;
    public static final int CalendarControl_dayWeekendShadowRadius = 34;
    public static final int CalendarControl_dayWeekendTextColor = 30;
    public static final int CalendarControl_dayWeekendTextSize = 31;
    public static final int CalendarControl_dowShadowColor = 15;
    public static final int CalendarControl_dowShadowDx = 12;
    public static final int CalendarControl_dowShadowDy = 13;
    public static final int CalendarControl_dowShadowRadius = 14;
    public static final int CalendarControl_dowTextColor = 10;
    public static final int CalendarControl_dowTextSize = 11;
    public static final int CalendarControl_gridLineColor = 50;
    public static final int CalendarControl_gridLinesVisible = 61;
    public static final int CalendarControl_maximumDate = 58;
    public static final int CalendarControl_minimumDate = 57;
    public static final int CalendarControl_selectedDrawable = 48;
    public static final int CalendarControl_selectedDrawableKeepSquare = 49;
    public static final int CalendarControl_selectedShadowColor = 56;
    public static final int CalendarControl_selectedShadowDx = 53;
    public static final int CalendarControl_selectedShadowDy = 54;
    public static final int CalendarControl_selectedShadowRadius = 55;
    public static final int CalendarControl_selectedTextColor = 51;
    public static final int CalendarControl_selectedTextSize = 52;
    public static final int CalendarControl_timeDefault = 60;
    public static final int CalendarControl_todayDrawable = 44;
    public static final int CalendarControl_todayDrawableKeepSquare = 45;
    public static final int CalendarControl_todayHighlighted = 62;
    public static final int CalendarControl_todaySelectedDrawable = 46;
    public static final int CalendarControl_todaySelectedDrawableKeepSquare = 47;
    public static final int CalendarControl_weekendSelectable = 59;
    public static final int CalendarControl_yearNavigationVisible = 63;
}
