package com.google.android.gms.internal;

import android.content.Context;
import com.google.android.gms.ads.internal.zzu;
import java.util.List;
import java.util.concurrent.TimeUnit;

@zzin
public final class zzdc {
    public static final zzcy zzaxx = zzcy.zza(0, "gads:sdk_core_experiment_id");
    public static final zzcy zzaxy = zzcy.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final zzcy zzaxz = zzcy.zza(0, "gads:request_builder:singleton_webview", (Boolean) false);
    public static final zzcy zzaya = zzcy.zza(0, "gads:request_builder:singleton_webview_experiment_id");
    public static final zzcy zzayb = zzcy.zza(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    public static final zzcy zzayc = zzcy.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzcy zzayd = zzcy.zza(0, "gads:sdk_crash_report_enabled", (Boolean) false);
    public static final zzcy zzaye = zzcy.zza(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    public static final zzcy zzayf = zzcy.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzcy zzayg = zzcy.zza(0, "gads:block_autoclicks", (Boolean) false);
    public static final zzcy zzayh = zzcy.zza(0, "gads:block_autoclicks_experiment_id");
    public static final zzcy zzayi = zzcy.zzb(0, "gads:prefetch:experiment_id");
    public static final zzcy zzayj = zzcy.zza(0, "gads:spam_app_context:experiment_id");
    public static final zzcy zzayk = zzcy.zza(0, "gads:spam_app_context:enabled", (Boolean) false);
    public static final zzcy zzayl = zzcy.zza(0, "gads:video_stream_cache:experiment_id");
    public static final zzcy zzaym = zzcy.zza(0, "gads:video_stream_cache:limit_count", 5);
    public static final zzcy zzayn = zzcy.zza(0, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzcy zzayo = zzcy.zza(0, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzcy zzayp = zzcy.zza(0, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzcy zzayq = zzcy.zza(0, "gads:video_stream_cache:notify_interval_millis", 1000);
    public static final zzcy zzayr = zzcy.zza(0, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzcy zzays = zzcy.zza(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final zzcy zzayt = zzcy.zza(0, "gads:video:metric_frame_hash_times", "");
    public static final zzcy zzayu = zzcy.zza(0, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzcy zzayv = zzcy.zzb(0, "gads:spam_ad_id_decorator:experiment_id");
    public static final zzcy zzayw = zzcy.zza(0, "gads:spam_ad_id_decorator:enabled", (Boolean) false);
    public static final zzcy zzayx = zzcy.zzb(0, "gads:looper_for_gms_client:experiment_id");
    public static final zzcy zzayy = zzcy.zza(0, "gads:looper_for_gms_client:enabled", (Boolean) true);
    public static final zzcy zzayz = zzcy.zza(0, "gads:sw_ad_request_service:enabled", (Boolean) true);
    public static final zzcy zzaza = zzcy.zza(0, "gads:sw_dynamite:enabled", (Boolean) true);
    public static final zzcy zzazb = zzcy.zza(0, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzcy zzazc = zzcy.zza(0, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzcy zzazd = zzcy.zza(0, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzcy zzaze = zzcy.zza(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final zzcy zzazf = zzcy.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzcy zzazg = zzcy.zza(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final zzcy zzazh = zzcy.zza(0, "gads:enable_content_fetching", (Boolean) true);
    public static final zzcy zzazi = zzcy.zza(0, "gads:content_length_weight", 1);
    public static final zzcy zzazj = zzcy.zza(0, "gads:content_age_weight", 1);
    public static final zzcy zzazk = zzcy.zza(0, "gads:min_content_len", 11);
    public static final zzcy zzazl = zzcy.zza(0, "gads:fingerprint_number", 10);
    public static final zzcy zzazm = zzcy.zza(0, "gads:sleep_sec", 10);
    public static final zzcy zzazn = zzcy.zza(0, "gad:app_index_enabled", (Boolean) true);
    public static final zzcy zzazo = zzcy.zza(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    public static final zzcy zzazp = zzcy.zza(0, "gads:app_index:timeout_ms", 1000);
    public static final zzcy zzazq = zzcy.zza(0, "gads:app_index:experiment_id");
    public static final zzcy zzazr = zzcy.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final zzcy zzazs = zzcy.zza(0, "gads:kitkat_interstitial_workaround:enabled", (Boolean) true);
    public static final zzcy zzazt = zzcy.zza(0, "gads:interstitial_follow_url", (Boolean) true);
    public static final zzcy zzazu = zzcy.zza(0, "gads:interstitial_follow_url:register_click", (Boolean) true);
    public static final zzcy zzazv = zzcy.zza(0, "gads:interstitial_follow_url:experiment_id");
    public static final zzcy zzazw = zzcy.zza(0, "gads:analytics_enabled", (Boolean) true);
    public static final zzcy zzazx = zzcy.zza(0, "gads:ad_key_enabled", (Boolean) false);
    public static final zzcy zzazy = zzcy.zza(0, "gads:webview_cache_version", 0);
    public static final zzcy zzazz = zzcy.zza(1, "gads:webview_recycle:enabled", (Boolean) false);
    public static final zzcy zzbaa = zzcy.zza(1, "gads:webview_recycle:experiment_id");
    public static final zzcy zzbab = zzcy.zzb(0, "gads:pan:experiment_id");
    public static final zzcy zzbac = zzcy.zza(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final zzcy zzbad = zzcy.zza(0, "gads:ad_manager_creator:enabled", (Boolean) true);
    public static final zzcy zzbae = zzcy.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final zzcy zzbaf = zzcy.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final zzcy zzbag = zzcy.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzcy zzbah = zzcy.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzcy zzbai = zzcy.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzcy zzbaj = zzcy.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzcy zzbak = zzcy.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzcy zzbal = zzcy.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final zzcy zzbam = zzcy.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzcy zzban = zzcy.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzcy zzbao = zzcy.zza(1, "gads:spherical_video:experiment_id");
    public static final zzcy zzbap = zzcy.zza(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final zzcy zzbaq = zzcy.zza(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final zzcy zzbar = zzcy.zza(1, "gads:include_local_global_rectangles:experiment_id");
    public static final zzcy zzbas = zzcy.zza(0, "gads:device_info_caching:enabled", (Boolean) true);
    public static final zzcy zzbat = zzcy.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final zzcy zzbau = zzcy.zza(0, "gads:gen204_signals:enabled", (Boolean) false);
    public static final zzcy zzbav = zzcy.zza(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    public static final zzcy zzbaw = zzcy.zza(0, "gads:adid_reporting:enabled", (Boolean) false);
    public static final zzcy zzbax = zzcy.zza(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    public static final zzcy zzbay = zzcy.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    public static final zzcy zzbaz = zzcy.zza(0, "gads:request_pkg:enabled", (Boolean) true);
    public static final zzcy zzbba = zzcy.zza(0, "gads:gmsg:disable_back_button:enabled", (Boolean) false);
    public static final zzcy zzbbb = zzcy.zza(0, "gads:gmsg:video_meta:enabled", (Boolean) true);
    public static final zzcy zzbbc = zzcy.zza(0, "gads:gmsg:video_meta:experiment_id");
    public static final zzcy zzbbd = zzcy.zza(0, "gads:network:cache_prediction_duration_s", 300);
    public static final zzcy zzbbe = zzcy.zza(0, "gads:mediation:dynamite_first:admobadapter", (Boolean) true);
    public static final zzcy zzbbf = zzcy.zza(0, "gads:mediation:dynamite_first:adurladapter", (Boolean) true);
    public static final zzcy zzbbg = zzcy.zza(0, "gads:ad_loader:timeout_ms", 60000);
    public static final zzcy zzbbh = zzcy.zza(0, "gads:rendering:timeout_ms", 60000);
    public static final zzcy zzbbi = zzcy.zza(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final zzcy zzbbj = zzcy.zza(1, "gads:gestures:task_timeout", 2000);
    public static final zzcy zzbbk = zzcy.zza(1, "gads:gestures:encrypt_size_limit:experiment_id");
    public static final zzcy zzbbl = zzcy.zza(1, "gads:gestures:encrypt_size_limit:enabled", (Boolean) true);
    public static final zzcy zzbbm = zzcy.zza(1, "gads:gestures:cpu:experiment_id");
    public static final zzcy zzbbn = zzcy.zza(1, "gads:gestures:cpu_query:enabled", (Boolean) false);
    public static final zzcy zzbbo = zzcy.zza(1, "gads:gestures:cpu_click:enabled", (Boolean) false);
    public static final zzcy zzbbp = zzcy.zza(1, "gads:gestures:jbk:experiment_id");
    public static final zzcy zzbbq = zzcy.zza(1, "gads:gestures:jbk_query:enabled", (Boolean) false);
    public static final zzcy zzbbr = zzcy.zza(1, "gads:gestures:jbk_click:enabled", (Boolean) false);
    public static final zzcy zzbbs = zzcy.zza(1, "gads:gestures:stk:experiment_id");
    public static final zzcy zzbbt = zzcy.zza(1, "gads:gestures:stk:enabled", (Boolean) false);
    public static final zzcy zzbbu = zzcy.zza(0, "gass:client:enabled", (Boolean) false);
    public static final zzcy zzbbv = zzcy.zza(0, "gass:client:experiment_id");
    public static final zzcy zzbbw = zzcy.zza(0, "gass:enabled", (Boolean) false);
    public static final zzcy zzbbx = zzcy.zza(0, "gass:enable_int_signal", (Boolean) true);
    public static final zzcy zzbby = zzcy.zza(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    public static final zzcy zzbbz = zzcy.zza(0, "gads:edu_device_helper:enabled", (Boolean) true);
    public static final zzcy zzbca = zzcy.zza(0, "gads:support_screen_shot", (Boolean) true);
    public static final zzcy zzbcb = zzcy.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", (Boolean) true);
    public static final zzcy zzbcc = zzcy.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    public static final zzcy zzbcd = zzcy.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzcy zzbce = zzcy.zza(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    public static final zzcy zzbcf = zzcy.zza(1, "gads:singleton_webview_native", (Boolean) false);
    public static final zzcy zzbcg = zzcy.zza(1, "gads:singleton_webview_native:experiment_id");
    public static final zzcy zzbch = zzcy.zza(1, "gads:enable_untrack_view_native", (Boolean) true);
    public static final zzcy zzbci = zzcy.zza(1, "gads:reset_listeners_preparead_native", (Boolean) true);
    public static final zzcy zzbcj = zzcy.zza(0, "gads:method_tracing:enabled", (Boolean) false);
    public static final zzcy zzbck = zzcy.zza(0, "gads:method_tracing:duration_ms", 30000);
    public static final zzcy zzbcl = zzcy.zza(0, "gads:method_tracing:count", 5);
    public static final zzcy zzbcm = zzcy.zza(0, "gads:method_tracing:filesize", 134217728);
    public static final zzcy zzbcn = zzcy.zza(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    public static final zzcy zzbco = zzcy.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzcy zzbcp = zzcy.zza(1, "gads:auto_location_timeout", 2000);
    public static final zzcy zzbcq = zzcy.zzb(1, "gads:auto_location_timeout:experiment_id");
    public static final zzcy zzbcr = zzcy.zza(1, "gads:auto_location_interval", -1);
    public static final zzcy zzbcs = zzcy.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzcy zzbct = zzcy.zza(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    public static final zzcy zzbcu = zzcy.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzcy zzbcv = zzcy.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final zzcy zzbcw = zzcy.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
    public static final zzcy zzbcx = zzcy.zza(0, "gads:afs:csa:experiment_id");
    public static final zzcy zzbcy = zzcy.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzcy zzbcz = zzcy.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzcy zzbda = zzcy.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzcy zzbdb = zzcy.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzcy zzbdc = zzcy.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzcy zzbdd = zzcy.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final zzcy zzbde = zzcy.zza(0, "gads:afs:csa_ad_manager_enabled", (Boolean) true);
    public static final zzcy zzbdf = zzcy.zza(0, "gads:safe_browsing:reporting:malicious:enabled", (Boolean) false);
    public static final zzcy zzbdg = zzcy.zza(0, "gads:safe_browsing:reporting:full:enabled", (Boolean) false);
    public static final zzcy zzbdh = zzcy.zza(0, "gads:safe_browsing:screenshot:enabled", (Boolean) false);
    public static final zzcy zzbdi = zzcy.zza(0, "gads:safe_browsing:reporting:url", "https://sb-ssl.google.com/safebrowsing/clientreport/malware");
    public static final zzcy zzbdj = zzcy.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    public static final zzcy zzbdk = zzcy.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    public static final zzcy zzbdl = zzcy.zza(0, "gads:safe_browsing:experiment_id");
    public static final zzcy zzbdm = zzcy.zza(0, "gads:safe_browsing:debug", (Boolean) false);
    public static final zzcy zzbdn = zzcy.zza(0, "gads:webview_cookie:enabled", (Boolean) true);

    public static void initialize(Context context) {
        zzkt.zzb(new C1531eo(context));
    }

    public static List zzjx() {
        return zzu.zzfy().zzjx();
    }

    public static List zzjy() {
        return zzu.zzfy().zzjy();
    }
}
