package com.google.android.gms.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzqq extends OptionalPendingResult {

    /* renamed from: a */
    private final zzpo f6917a;

    public zzqq(PendingResult pendingResult) {
        if (!(pendingResult instanceof zzpo)) {
            throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
        }
        this.f6917a = (zzpo) pendingResult;
    }

    public Result await() {
        return this.f6917a.await();
    }

    public Result await(long j, TimeUnit timeUnit) {
        return this.f6917a.await(j, timeUnit);
    }

    public void cancel() {
        this.f6917a.cancel();
    }

    public Result get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public boolean isCanceled() {
        return this.f6917a.isCanceled();
    }

    public boolean isDone() {
        return this.f6917a.isReady();
    }

    public void setResultCallback(ResultCallback resultCallback) {
        this.f6917a.setResultCallback(resultCallback);
    }

    public void setResultCallback(ResultCallback resultCallback, long j, TimeUnit timeUnit) {
        this.f6917a.setResultCallback(resultCallback, j, timeUnit);
    }

    public TransformedResult then(ResultTransform resultTransform) {
        return this.f6917a.then(resultTransform);
    }

    public void zza(PendingResult.zza zza) {
        this.f6917a.zza(zza);
    }

    public Integer zzaoj() {
        return this.f6917a.zzaoj();
    }
}
